# Generated by Django 5.0.1 on 2024-02-08 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('code_str', models.CharField(default='tYuxBtn50Su:8><Iyk_uWY6jZRFGP_yUR_V=pU_>@pgcY98D[>CI:G64]gjb_qXU', max_length=64, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='referralcode',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user', 'active'), name='unique_active_code_for_user'),
        ),
    ]
